[platformio]
default_envs = native
test_dir = firmware/tests
src_dir = firmware/main

[env:native]
platform = native
test_framework = unity
test_build_src = true
build_src_filter = -<*> +<Actuators.cpp> +<SystemState.cpp>
build_flags =
    -I firmware/shared/BiomassConfig/src
    -I firmware/main
extra_scripts = pre:test_filter.py
