name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Cache Arduino data
        uses: actions/cache@v6
        with:
          path: |
            ~/.arduino15
            ~/.core-simulator
          key: ${{ runner.os }}-arduino-${{ hashFiles('firmware/install_deps.sh') }}
          restore-keys: |
            ${{ runner.os }}-arduino-

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v2

      - name: Install ESP32 Core and Dependencies
        run: ./firmware/install_deps.sh

      - name: Compile Sketches
        run: arduino-cli compile --profile esp32 --warnings all firmware/main/
