name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Arduino data
        uses: actions/cache@v4
        with:
          path: |
            ~/.arduino15
            ~/.core-simulator
          key: ${{ runner.os }}-arduino-${{ hashFiles('firmware/sketch.yaml') }}
          restore-keys: |
            ${{ runner.os }}-arduino-

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v2

      - name: Compile Sketches
        uses: arduino/compile-sketches@v1
        with:
          fqbn: esp32:esp32:esp32
          sketch-paths: |
            firmware
          cli-compile-flags: |
            - --profile
            - esp32
            - --warnings
            - all
