name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Arduino data
        uses: actions/cache@v4
        with:
          path: |
            ~/.arduino15
            ~/.core-simulator
          key: ${{ runner.os }}-arduino-${{ hashFiles('firmware/sketch.yaml') }}
          restore-keys: |
            ${{ runner.os }}-arduino-

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v2

      - name: Install ESP32 Core and Dependencies
        run: |
          arduino-cli core update-index --additional-urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
          arduino-cli core install esp32:esp32@2.0.11 --additional-urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
          arduino-cli lib install "Adafruit PM25 AQI Sensor@2.0.0" "DHT sensor library@1.4.7"

      - name: Compile Sketches
        run: arduino-cli compile --profile esp32 --warnings all firmware/
